# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_reconciled_at_payment_reconciled_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("SUCCESS", "Réussi"),
                    ("FAILED", "Échoué"),
                    ("CANCELLED", "Annulé"),
                    ("REFUNDED", "Remboursé"),
                    ("DISPUTED", "Contesté"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]