# Generated by Django 6.1 on 2026-08-18 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.SlugField(unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'niveau',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='commune')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "zone d'intervention",
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'matière',
                'verbose_name_plural': 'matières',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeachingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('code', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': "mode d'enseignement",
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
                ('levels', models.ManyToManyField(blank=True, related_name='learners', to='profiles.level')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_learners', to='profiles.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('headline', models.CharField(blank=True, max_length=160, verbose_name='titre professionnel')),
                ('bio', models.TextField(blank=True, max_length=2000, verbose_name='présentation')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name="années d'expérience")),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tarif horaire')),
                ('currency', models.CharField(default='CDF', editable=False, max_length=3, verbose_name='devise')),
                ('languages', models.CharField(blank=True, max_length=250, verbose_name='langues')),
                ('is_public', models.BooleanField(default=False, verbose_name='profil public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('levels', models.ManyToManyField(blank=True, related_name='teachers', to='profiles.level')),
                ('service_areas', models.ManyToManyField(blank=True, related_name='teachers', to='profiles.servicearea')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='profiles.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
                ('teaching_modes', models.ManyToManyField(blank=True, related_name='teachers', to='profiles.teachingmode')),
            ],
            options={
                'verbose_name': 'profil enseignant',
                'ordering': ('user__first_name', 'user__last_name', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='jour')),
                ('start_time', models.TimeField(verbose_name='début')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='profiles.teacherprofile')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
                'constraints': [models.UniqueConstraint(fields=('teacher', 'weekday', 'start_time', 'end_time'), name='unique_teacher_availability'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start')],
            },
        ),
    ]
