# Generated by Django 6.1 on 2026-08-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerprofile',
            options={'ordering': ('user__email',), 'verbose_name': 'profil apprenant'},
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='preferred_service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='profiles.servicearea'),
        ),
    ]
