# Generated by Django 6.1 on 2026-08-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_learnerprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('key', '-version'),
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_configuration_version')],
            },
        ),
    ]
