# Generated by Django 6.1 on 2026-08-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='compte interne'),
        ),
    ]
