# Generated by Django 6.1 on 2026-08-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_session_and_terminal_statuses'),
        ('learning', '0005_learningevent_review_created'),
        ('messaging', '0002_report_external_targets'),
        ('profiles', '0002_seed_catalog'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_target',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_single_target',
        ),
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('conversation__isnull', False), ('teacher_profile__isnull', False), ('proposal__isnull', False), ('booking__isnull', False), ('review__isnull', False), _connector='OR'), name='report_has_target'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', False), ('teacher_profile__isnull', False)), models.Q(('conversation__isnull', False), ('proposal__isnull', False)), models.Q(('booking__isnull', False), ('conversation__isnull', False)), models.Q(('conversation__isnull', False), ('review__isnull', False)), models.Q(('proposal__isnull', False), ('teacher_profile__isnull', False)), models.Q(('booking__isnull', False), ('teacher_profile__isnull', False)), models.Q(('review__isnull', False), ('teacher_profile__isnull', False)), models.Q(('booking__isnull', False), ('proposal__isnull', False)), models.Q(('proposal__isnull', False), ('review__isnull', False)), models.Q(('booking__isnull', False), ('review__isnull', False)), _connector='OR', _negated=True), name='report_has_single_target'),
        ),
    ]
