# Generated by Django 6.1 on 2026-08-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_report_assignee_report_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_REVIEW', 'En cours'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Classé'), ('WARNED', 'Averti'), ('SUSPENDED', 'Suspendu'), ('RESTORED', 'Restauré')], default='OPEN', max_length=10),
        ),
    ]
