# Generated by Django 6.1 on 2026-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_REVIEW', 'En cours'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Classé')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportaction',
            name='action',
            field=models.CharField(choices=[('VIEWED', 'Consulté'), ('IN_REVIEW', 'Pris en charge'), ('RESOLVED', 'Résolu'), ('DISMISSED', 'Classé'), ('WARNED', 'Averti'), ('SUSPENDED', 'Suspendu'), ('RESTORED', 'Restauré')], max_length=12),
        ),
    ]
