# Generated by Django 6.1 on 2026-08-18 14:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget maximal')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='date souhaitée')),
                ('preferred_start_time', models.TimeField(blank=True, null=True, verbose_name='heure souhaitée')),
                ('frequency', models.CharField(choices=[('ONCE', 'Une fois'), ('WEEKLY', 'Chaque semaine'), ('INTENSIVE', 'Programme intensif')], default='ONCE', max_length=10)),
                ('description', models.TextField(max_length=2000, verbose_name='besoin')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('MATCHED', 'Correspondances trouvées'), ('CLOSED', 'Fermée')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_requests', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='profiles.level')),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='profiles.servicearea')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='profiles.subject')),
                ('teaching_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='profiles.teachingmode')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='learning.learningrequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='profiles.teacherprofile')),
            ],
            options={
                'ordering': ('-score', 'teacher__user__first_name'),
                'constraints': [models.UniqueConstraint(fields=('learning_request', 'teacher'), name='unique_request_teacher_match')],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(max_length=1500)),
                ('status', models.CharField(choices=[('SENT', 'Envoyée'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('WITHDRAWN', 'Retirée')], default='SENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='learning.learningrequest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='profiles.teacherprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('learning_request', 'teacher'), name='unique_teacher_proposal_per_request')],
            },
        ),
    ]
