# Generated by Django 6.1 on 2026-08-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('request.created', 'Demande créée'), ('match.created', 'Matching créé'), ('proposal.sent', 'Proposition envoyée')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_events', to=settings.AUTH_USER_MODEL)),
                ('learning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='learning.learningrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
