# Generated by Django 6.1 on 2026-08-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='name',
            field=models.CharField(choices=[('request.created', 'Demande créée'), ('match.created', 'Matching créé'), ('proposal.sent', 'Proposition envoyée'), ('booking.created', 'Réservation créée')], max_length=30),
        ),
    ]
