# Generated by Django 6.1 on 2026-08-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningevent_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevent',
            name='name',
            field=models.CharField(choices=[('request.created', 'Demande créée'), ('match.created', 'Matching créé'), ('proposal.sent', 'Proposition envoyée'), ('booking.created', 'Réservation créée'), ('session.completed', 'Session terminée'), ('review.created', 'Avis créé'), ('payment.completed', 'Paiement terminé')], max_length=30),
        ),
    ]
