# Generated by Django 6.1 on 2026-08-25 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_learningevent_name'),
        ('profiles', '0002_seed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='learningrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('preferred_date__isnull', True), ('preferred_start_time__isnull', True)), models.Q(('preferred_date__isnull', False), ('preferred_start_time__isnull', False)), _connector='OR'), name='learning_request_complete_time_slot'),
        ),
    ]
