# Generated by Django 6.1 on 2026-08-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_proposal_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Vérification email'), ('MATCH_CREATED', 'Nouveau match'), ('PROPOSAL_CREATED', 'Nouvelle proposition'), ('SESSION_REMINDER_24H', 'Rappel de session 24 h'), ('SESSION_REMINDER_1H', 'Rappel de session 1 h'), ('PROPOSAL_ACCEPTED', 'Proposition acceptée'), ('PROPOSAL_REJECTED', 'Proposition refusée'), ('BOOKING_CREATED', 'Réservation créée'), ('PAYMENT_COMPLETED', 'Paiement confirmé'), ('SESSION_COMPLETED', 'Session terminée'), ('REVIEW_REQUESTED', 'Avis à publier'), ('REVIEW_CREATED', 'Nouvel avis')], max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('booking_reminders', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
