# Generated by Django 6.1 on 2026-08-27 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_proposal_availability_events'),
        ('notifications', '0003_alter_notification_kind_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='learning_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='learning.learningrequest'),
        ),
    ]
