# Generated by Django 6.1 on 2026-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_learning_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Vérification email'), ('MATCH_CREATED', 'Nouveau match'), ('PROPOSAL_CREATED', 'Nouvelle proposition'), ('SESSION_REMINDER_24H', 'Rappel de session 24 h'), ('SESSION_REMINDER_1H', 'Rappel de session 1 h'), ('PROPOSAL_ACCEPTED', 'Proposition acceptée'), ('PROPOSAL_REJECTED', 'Proposition refusée'), ('BOOKING_CREATED', 'Réservation créée'), ('PAYMENT_COMPLETED', 'Paiement confirmé'), ('SESSION_COMPLETED', 'Session terminée'), ('REVIEW_REQUESTED', 'Avis à publier'), ('REVIEW_CREATED', 'Nouvel avis'), ('VERIFICATION_UPDATED', 'Vérification mise à jour')], max_length=32),
        ),
    ]
